---
- name: Reap old instances
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    filter_regions:
      - ap-northeast-1
      - ap-northeast-2
      - ap-south-1
      - ap-southeast-1
      - ap-southeast-2
      - ca-central-1
      - eu-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - sa-east-1
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
    filter_dates:
#      - 2012 # scanned, nothing
#      - 2013 # scanned, nothing
#      - 2014 # scanned, nothing
#      - 2015 # scanned, nothing
#      - 2016 # scanned, nothing
#      - 2017 # scanned, nothing
      - 2018
      - 2019
      - 2020-01

  tasks:
    - name: Loop through regions and dates
      include_tasks: find_instances.yml
      loop: "{{ filter_regions |product(filter_dates)|list }}"
      loop_control:
        loop_var: outer_item

